### ISSUE TITLE
Holmake error

### ISSUE THREAD

**Issue by FDSouthern** [HeikoBecker/Lassie#1]
I'm not an experienced user of HOL, but I have just discovered Lassie and I want to report an issue I encountered during installation.

I installed HOL4 from the Git repository (last commit 3edcbc777128607e6531b78601e9e0e191183079) and I followed the instructions for installing Lassie in the README.

Everything was successful up to and including the ant invocation.
When I ran Holmake, I got a type error on the following line: https://github.com/HeikoBecker/Lassie/blob/ae0fd48244c3c42e609cf75e2d4227935e7e342f/src/LassieParserLib.sml#L69 

The error was:
> error in load Lassie/src/LassieParserLib : Fail "Static Errors"
> error in load Lassie/src/LassieLib : Fail "Static Errors"  
>  error in load Lassie/src/LassieTestScript : Fail "Static Errors"  
>  Lassie/src/LassieParserLib.sml:69: error: Can't unify 'a * 'b to thm * DB_dtype.class * {private: bool}  
>     (Different number of fields)  
>  Found near  
>    case List.find cmp (DB.listDB ()) of  
>       NONE => NONE |  
>       SOME (_, ...) => SOME th  
>  Uncaught exception: Fail "Static Errors"

I simply updated the offending line to
`| SOME (_, (th, _, _)) =>  SOME th`
and everything seems to work as intended.
I assume that there has been a change in the DB format in HOL and Lassie needs to be updated accordingly.
I apologise if I'm mistaken and this issue has been opened in error.

Thank you.

**Comment by FDSouthern** [comment]
Somewhat awkwardly, I've just noticed that Lassie is included in the HOL4 source tree, although when I try and build that I get a completely different Java error, which I suppose should be reported to the HOL repository if it is not already known.

It may be worth updating this repo to mention that Lassie is now in the main HOL4 repository?

**Comment by HeikoBecker** [comment]
Thanks for noticing (and sorry for the late reply). Indeed, the code in this repository has been deprecated in favor of the HOL4 source version. I will update the readme accordingly.
